name: scTemplate
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/osx-arm64/
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.10
  - pyyaml=6.0
  - pip:
      - anticor-features==0.2.0
      - doubletdetection==4.2
      - harmonypy==0.0.9
      - openpyxl==3.1.1
      - scanpy==1.9.3