Info:
  sample_key: null
QC:
  doublet_removal: False
  min_genes: 200
  min_cells: 10
  normalization: PFlog1pPF
  feature_selection: seurat_v3
  number_features: 3000
  scale: True
  n_genes_by_counts: null
  mt_threshold: null
  rb_threshold: null
  hb_threshold: null
  remove_mt: False
  remove_rb: False
  remove_hb: False
  remove_custom_genes : null
BatchEffectCorrection:
  method: null
  batch_key: null
NeighborhoodGraph:
  n_neighbors: 15
  n_pcs: null
Clustering:
  method: leiden
  resolution: 1.0
DiffGeneExp:
  method: wilcoxon