Info:
  batch_key: null
  sample_key: null
QC:
  doublet_removal: False
  min_genes: 200
  min_cells: 10
  normalization: PFlog1pPF
  feature_selection: seurat_v3
  number_features: 2000
  scale: True
  n_genes_by_counts: 3000
  mt_threshold: 20
  rb_threshold: 15
  hb_threshold: 1
  remove_mt: True
  remove_rb: True
  remove_hb: True
  remove_custom_genes : null
BatchEffectCorrection:
  method: null
  batch_key: Patient
Preprocessing:
  NeighborhoodGraph:
    n_neighbors: 15
    n_pcs: null
  DimRed: null
Clustering:
  method: leiden
  resolution: 1.0
DiffGeneExp:
  method: wilcoxon